{% set name = "casadi" %}
{% set version = "3.1.1" %}
{% set variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/casadi/casadi/archive/{{ version }}.tar.gz
  sha256: 335eab9270a06d18134dafe34b5a21fe26fe6926611d7f960d826d82e851abef

build:
  number: 1
  skip: true  # [win]
  skip: true  # [np==111]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - pkg-config  # [osx]
    - cmake
    - python
    - swig
    - numpy x.x
    - gcc
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*
    - ipopt

  run:
    - python
    - numpy x.x
    - libgcc
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*
    - ipopt

test:
  imports:
    - casadi
  files:
    - ipopt_nl.py
  commands:
    python ipopt_nl.py

about:
  home: http://casadi.org
  license: LGPL-3.0
  summary: 'CasADi is a symbolic framework for numeric optimization'

extra:
  recipe-maintainers:
    - pstjohn
