travis:
  secure:
    BINSTAR_TOKEN: jtyvxpdpoom/iuaTAOZyK+0DjY2QTcOc0gYAcHsbUeKSSIsEaHX6gCW18oT6Kr0BcYtwC1fOnqXip2jXWBQFzoPq/XyBqbLck2ckfyuUTJfNzv9Z0tdqAmkoFQsEzy5yVI4fKQiLqWrTkAbH3yNcnGVLJhXcwWpY2elAV9158LrjrS+nk1xaqmEXCQse48fpTVRg9bIEo2UfyWUgfI11Q1CofBW0hvLZaCtU25mUC9PqBgy2bsuIMOxeaNWPBl/HU2FUfh9Q8RZpUPNwPzWaINCyytG29etnYaTTl6K3U+/X5dadjApFYTTVlL/lgX5kYM4H+Jds9IeMA2r1Mjg2o+QxkFQT8yKkPo+WsEWWXFpUqgeUGrDiYJr3Ioj6R26tVRynjCAWZPXCXHbOt6coqwXYfu+UGE6uZSuLz35WOdLnjoFVWJS2AvbTCiRl+5vDe2snfsW02AfHc1TFglgtjBRjJ4jVY1Rtdv7XgnllWeLrJqmpF/mxqX7U/tAkFS/2ccof+MYV/Nx+aBSCYLiqA7aXTtxD7103J5cIzCIyBquvOpuq3Agq5phjYn2PR7QVMmcgBTgqE5wUH7Yo+FTrDE38LSPah2RP+lOayJlIiVxMODCGmmhlyUxl/8CXKZQLqEszcop0w9k1OS5OSIWApSdc7+epclGGFehrheLy4LI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
conda_forge_output_validation: true
